name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-android:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
  
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew composeApp:assembleRelease
        
      - name: Upload the Artifact
        uses: actions/upload-artifact@v4.5.0
        with:
          name: android-apk
          path: composeApp/build/outputs/apk/release/*.apk

  build-desktop-linux:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew composeApp:packageReleaseDistributionForCurrentOS
      
      - name: Upload the Artifact
        uses: actions/upload-artifact@v4.5.0
        with:
          name: debian-package
          path: composeApp/build/compose/binaries/main-release/deb/*.deb

  build-desktop-macos:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew composeApp:packageReleaseDistributionForCurrentOS
      
      - name: Upload the Artifact
        uses: actions/upload-artifact@v4.5.0
        with:
          name: macos-package
          path: composeApp/build/compose/binaries/main-release/dmg/*.dmg

  build-desktop-windows:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew composeApp:packageReleaseDistributionForCurrentOS
      
      - name: Upload the Artifact
        uses: actions/upload-artifact@v4.5.0
        with:
          name: windows-package
          path: composeApp/build/compose/binaries/main-release/exe/*.exe

  publish:
    name: Publish Release
    needs: [build-android, build-desktop-linux, build-desktop-macos, build-desktop-windows]
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4.1.8
      - name: Publish release
        uses: ghalactic/github-release-from-tag@v5
        with:
          assets: |
            - path: ${{ github.workspace }}/*.zip
